"""Create table Todos

Revision ID: 157e2d37294b
Revises: 24fcc8b4badb
Create Date: 2022-08-05 07:22:09.614792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157e2d37294b'
down_revision = '24fcc8b4badb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('todo', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_ad', sa.DateTime(), nullable=True),
    sa.Column('updated_ad', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todos_created_ad'), 'todos', ['created_ad'], unique=False)
    op.create_index(op.f('ix_todos_updated_ad'), 'todos', ['updated_ad'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todos_updated_ad'), table_name='todos')
    op.drop_index(op.f('ix_todos_created_ad'), table_name='todos')
    op.drop_table('todos')
    # ### end Alembic commands ###
