"""Create table Produk

Revision ID: 1934c14e6025
Revises: a6fff05f8c4a
Create Date: 2022-08-05 07:23:32.347742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1934c14e6025'
down_revision = 'a6fff05f8c4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('kd', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.String(length=200), nullable=False),
    sa.Column('jumlah', sa.BigInteger(), nullable=False),
    sa.Column('harga', sa.Float(), nullable=False),
    sa.Column('kd_cat', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['kd_cat'], ['category_product.kd_cat'], ),
    sa.PrimaryKeyConstraint('kd')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
