"""Alter table Todos

Revision ID: 84130af13acc
Revises: 1934c14e6025
Create Date: 2022-08-16 10:05:26.053252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84130af13acc'
down_revision = '1934c14e6025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('token_acces', sa.Text(), nullable=True))
    op.add_column('todos', sa.Column('token_refresh', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'token_refresh')
    op.drop_column('todos', 'token_acces')
    # ### end Alembic commands ###
