"""Create table Category

Revision ID: a6fff05f8c4a
Revises: 157e2d37294b
Create Date: 2022-08-05 07:23:01.526048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6fff05f8c4a'
down_revision = '157e2d37294b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_product',
    sa.Column('kd_cat', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('kd_cat')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_product')
    # ### end Alembic commands ###
